version: '3.9'

services:
  couchdb:
    image: public.ecr.aws/medic/cht-couchdb:4.2.2
    volumes:
      - ${COUCHDB_DATA:-./srv}:/opt/couchdb/data
      - cht-credentials:/opt/couchdb/etc/local.d/
    environment:
      - "COUCHDB_USER=${COUCHDB_USER:-admin}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-pass}"
      - "COUCHDB_SECRET=${COUCHDB_SECRET}"
      - "COUCHDB_UUID=${COUCHDB_UUID}"
      - "SVC_NAME=${SVC_NAME:-couchdb}"
      - "COUCHDB_LOG_LEVEL=${COUCHDB_LOG_LEVEL:-debug}"
    restart: always
    ports:
      - "25984:5984"
    deploy:
      resources:
        limits:
          cpus: ${NBR_CPU:-'4'}


volumes:
  cht-credentials:
